-- COMANDOS BÁSICOS
SHOW DATABASES; -- MOSTRA OS BANCOS DE DADOS DISPONÍVEIS
CREATE DATABASE sql_estudo; -- CRIA UMA DATABASE
USE sql_estudo; -- USAR UM BANCO DE DADOS
SHOW TABLES; -- MOSTRAR TABELAS

-- COMO CRIAR UMA TABELA
CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR (255) NOT NULL,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ABRIR TABELA (TODAS AS COLUNAS)
SELECT * FROM users;

-- SELECIONAR COLUNA ESPECÍFICA 
SELECT username FROM users;

-- SELECIONAR COM CONDICIONAL, PARA RESULTADO ESPECÍFICO (user1)
SELECT * FROM users WHERE USERNAME = 'user1';

-- INSERINDO DADOS
INSERT INTO users (username, password) VALUES ('user2', '321');

-- COMO ATUALIZAR DADOS
UPDATE users SET PASSWORD = 'newpass' WHERE USERNAME = 'user1';

-- COMO APAGAR DADOS
DELETE FROM users WHERE username = 'user1';

-- TIPOS BÁSICOS DE DADOS
--INT: Intefer Values
--VARCHAR(n): Variable-length string with a max length of n
--TEXT: Long text data
--TIMESTAMP: Date ant time

-- IMPROVE QUERY PERFORMANCE WITH INDEXES
CREATE INDEX idx_username ON users (username);

--INNER JOIN
SELECT * FROM users
INNER JOIN orders ON users.id = orders.user_id;

--LEFT JOIN
SELECT * FROM users
LEFT JOIN orders ON users.id = orders.user_id;

-- BACKUP
